### PR TITLE
updates to libpinproc (lamps, compilation issues)

### PR DESCRIPTION
**Pull request by tomlogic**
I incorporated changes from koen (and unintentionally included a bunch of whitespace changes) that address a dim lamps issue with WPC and using DriverAuxSendCommands() to a P3-ROC.  I've also made changes to correct compilation issues under Linux.

### CODE REVIEW

**Comment by gstellenberg** [comment]
The whitespace changes make this extremely difficult to review.  

The only change I'm really concerned about is the ftdi.h one.  This will likely break anybody that didn't have problems before, and I haven't heard of anybody having trouble recently.  I personally have built a number of times in linux recently without issue.

**Comment by tomlogic** [comment]
Gerry,

Gabe's install script for Linux seems to contain a hack to work around the ftdi issue -- it uses `find` to locate the ftdi.h file and then adds that path to the include search path.  With my patch, that hack is no longer required.

I think you'll find that if you make my change to one of your Linux setups, it will still build.  When I build and install libftdi1, it places ftdi.h in that location.  An ftdi.h found at a higher level might actually be left over from a libftdi 0.x install.

Apologies on the whitespace changes -- I accidentally pulled them in with one of Koen's patches.  You should be able to find a diff view where you ignore whitespace changes to see the key content changes.

**Comment by mike-mcgann** [comment]
I can confirm that this fixed the issue with the dim lamps on a WPC. It would be nice to at least see those changes merged in some way.

**Comment by preble** [comment]
@tomlogic Thanks for submitting this PR. A number of the changes in it are no-brainers to merge (stdlib/`NULL`, the printf fixes). It would be best to break the commits in this PR up into about three individual PRs (Koen's changes, printf and null, and the ftdi include change) so we can get the parts of it in where there is no concern (those aforementioned no-brainers). The other parts that seem less certain, such as the libftdi path, can then be discussed separately.

As for the whitespace, yes there are tools to deal with it (github's diff viewer is decent in this respect), but I strongly prefer that we not merge that commit (410676d1a0c17c11ed0fab1c76a2027e660227cd) as-is because it will pollute the blame and make it more difficult to look back through the repo in the future. Better to go through the mild hassle of making a new commit with the good parts so that future maintenance will be better for all of us.

**Comment by tomlogic** [comment]
Adam, I'll rework the commits by the end of this week to allow for a merge of the "no-brainers", without any whitespace changes lumped in.  Then a separate pull request for ftdi.h path change.

**Comment by preble** [comment]
Thanks, Tom! I appreciate it.

**Comment by tomlogic** [comment]
OK, I've changed the commits for the pull request to just contain the no-brainers, and to remove the whitespace changes from Koen's P3-ROC change.  I'll hold off on pushing the libftdi header file change until after you merge this commit (I should have created a new branch specifically for this pull request).

**Comment by preble** [comment]
Thanks, @tomlogic!

**Pull request merged**
